[package]
name = "proust"
version = "0.0.1"
authors = ["Cl√©ment Delafargue <clement@delafargue.name>", "Geoffroy Couprie <contact@geoffroycouprie.com>"]

[dependencies.nom]
git = "https://github.com/Geal/nom.git"
