[package]
name = "proust"
version = "0.0.1"
authors = ["Cl√©ment Delafargue <clement@delafargue.name>", "Geoffroy Couprie <contact@geoffroycouprie.com>"]

[dependencies]
nom = "~0.3.1"
mio = "0.3.0"

[dependencies.mmap]
git = "https://github.com/Geal/rust-mmap.git"
